samples: /gpfs/project/projects/medbioinf/projects/mihen108/strand-seq-graph-phasing_testing/config/samples.tsv
# modify this to be some sort of num alignments?
segmentLengthThreshold: 1000000

# currently only applies to the R environment rules
deploy_offline: True
singularity_Renv: /gpfs/project/projects/medbioinf/projects/mihen108/env_Renv2.sif