### Note: SS read names should not have "_" character

sample: HG00733subset
assembly: /gpfs/project/projects/medbioinf/projects/mihen108/input/HG00733/assembly/HG00733_hgsvc_pbsq2-ccs_1000.r_utg.gfa
strandseq_dir: /gpfs/project/projects/medbioinf/projects/mihen108/input/HG00733/strandseq
strandseq_suffix: .fastq.gz
## Cheat on SaarClust
cheating: TRUE
# tools
# Rscript: /usr/local/package/bin/Rscript
# #whatshap_split : ../../tools/whatshap-fork/whatshap/cli/split.py
whatshap_split : utils/split.py
# #hifiasm: ../../tools/hifiasm/hifiasm
# assembly: verkko_test_graph
# BubbleGun: utils/split.py # ~/.local/bin/BubbleGun
#
# # long reads
# long_reads_dir: /gpfs/project/projects/medbioinf/projects/mihen108/input/
#
# # directory including all Strand-seq fastq files
# SS_fastq_dir: ../../ss_fastq
#
reference: /gpfs/project/projects/medbioinf/projects/mihen108/input/references/GRCh38_HGSVC2_noalt.fasta
#
# phased_vcf_dir: ../../ground-true-phasing/
# vcf_prefix: PR05
#
# # SS bams and phased vcf files
# #SS_bam_dir: ../../ss_bams
#
# bubble_info: "TRUE"
# evaluation: "FALSE"
#
# saarclust parameters
testNumClustersHard: [50,60,80,90,100,200]
numClustersHard: 4
numClustersSoft: 4
EMiter: 100
alpha: 0.01
minLib: 1
upperQ: 1 #0.95
logLth: 1
theta_constrain: "FALSE"
log_scale: "TRUE"
filter_soft_clust_input: "FALSE"
numAlignments: 30000 #150000

num_chromosomes: 2
