samples: /absolute/path/to/strand-seq-graph-phasing/config/samples.tsv
scripts_dir: /absolute/path/to/strand-seq-graph-phasing/scripts/
reference: /absolute/path/to/references/T2Tv11_hg002Yv2_chm13.fasta
segmentLengthThreshold: 250000
per_thread_memory: False

# currently only applies to the R Bioconductor environment rules
deploy_offline: True
singularity_Renv: /absolute/path/to/singularity_environment/env_Renv2.sif

# experimental features
calc_breakpoints: True

plot_evaluation: True
plot_width: 20
plot_height: 15