### Note: SS read names should not have "_" character
sample: HG002v11nl96slt1e6
assembly: /gpfs/project/projects/medbioinf/projects/mihen108/input/HG002/assembly_v1-1/assembly.homopolymer-compressed.gfa
num_components: 25

strandseq_dir: /gpfs/project/projects/medbioinf/projects/mihen108/input/HG002/strandseq
strandseq_suffix: .fastq.gz
# For verifiation
reference: /gpfs/project/projects/medbioinf/projects/mihen108/input/references/T2Tv11_hg002Yv2_chm13.fasta

numLibs: 96
# saarclust parameters
segmentLengthThreshold: 1000000
EMiter: 100
