### Note: SS read names should not have "_" character
sample: HG002tester
assembly: /gpfs/project/projects/medbioinf/projects/mihen108/input/HG002/assembly_v1-1/assembly.homopolymer-compressed.gfa

strandseq_dir: /gpfs/project/projects/medbioinf/projects/mihen108/input/HG002/strandseq
strandseq_suffix: .fastq.gz

segmentLengthThreshold: 1000000

# currently only applies to the R environment rules
deploy_offline: True
singularity_Renv: /gpfs/project/projects/medbioinf/projects/mihen108/env_Renv2.sif